spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/eventeum
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #hibernate.ddl-auto: validate
    hibernate.ddl-auto: create
eventStore:
  type: DB
database:
  type: SQL
ethereum:
  nodes:
    - name: default
      url: ws://localhost:8545
      blockStrategy: PUBSUB
broadcaster:
  type: HTTP
  http:
    contractEventsUrl: http://localhost:8080/_internal/events
    blockEventsUrl: http://localhost:8080/_internal/blocks
  event:
    confirmation:
      numBlocksToWait: 0
      numBlocksToWaitForMissingTx: 100
